apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
# prometheus-adapter
- prometheus-adapter-roleBindingAuthReader.yaml
# prometheus
- prometheus-roleSpecificNamespaces.yaml
- prometheus-roleBindingSpecificNamespaces.yaml
