apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- namespace.yaml

bases:
- base/alertmanager
- base/blackbox
- base/node-exporter
- base/grafana
- base/kube-state-metrics
- base/prometheus
- base/prometheus-adapter
- base/prometheus-operator
- monitors

# namespace
namespace: monitoring

# # 为所有资源添加标签
# commonLabels:
#   component: monitor
#   owner: andrew

# grafana 设置 admin 账号初始密码
secretGenerator:
- name: grafana-login-secret
  namespace: monitoring
  behavior: merge
  literals:
  - username=admin
  - password=p@ssw0rd

images:
# blackbox
- name: blackbox-exporter
  newName: quay.io/prometheus/blackbox-exporter
  newTag: v0.19.0
- name: configmap-reload
  newName: jimmidyson/configmap-reload
  newTag: v0.5.0
- name: kube-rbac-proxy
  newName: quay.io/brancz/kube-rbac-proxy
  newTag: v0.10.0
# grafana
- name: grafana
  newName: grafana/grafana
  newTag: 8.0.3
# node-exporter
- name: node-exporter
  newName: quay.io/prometheus/node-exporter
  newTag: v1.1.2
- name: kube-rbac-proxy
  newName: quay.io/brancz/kube-rbac-proxy
  newTag: v0.10.0
# kube-state-metrics
- name: kube-state-metrics
  # newName: k8s.gcr.io/kube-state-metrics/kube-state-metrics
  # newTag: v2.1.0
  newName: bitnami/kube-state-metrics
  newTag: 2.1.0
- name: kube-rbac-proxy
  newName: quay.io/brancz/kube-rbac-proxy
  newTag: v0.10.0
# prometheus-adapter
- name: k8s-prometheus-adapter
  newName: directxman12/k8s-prometheus-adapter
  newTag: v0.8.4

# replicas:
# - name: grafana
#   count: 1
# - name: kube-state-metrics
#   count: 1
# - name: prometheus-adapter
#   count: 1

patchesStrategicMerge:
# alertmanager
- overlays/alertmanager/alertmanager.yaml
- overlays/alertmanager/service.yaml
# grafana
- overlays/grafana/deployment.yaml
- overlays/grafana/service.yaml
# prometheus
- overlays/prometheus/prometheus.yaml
- overlays/prometheus/service.yaml
# prometheus-operator
- overlays/prometheus-operator/deployment.yaml
