apiVersion: v1
kind: Service
metadata:
  name: mysql-exporter
  namespace: monitoring
  labels:
    app.kubernetes.io/instance: mysql-exporter
spec:
  type: ClusterIP
  ports:
  - port: 9104
    targetPort: 9104
    protocol: TCP
    name: mysql-exporter
  selector:
    app.kubernetes.io/instance: mysql-exporter
