apiVersion: v1
kind: Service
metadata:
  name: prometheus-k8s
  namespace: monitoring
spec:
  ports:
  - name: web
    port: 9090
    targetPort: web
  selector:
    app: prometheus
    operator.prometheus.io/name: prometheus-k8s
    operator.prometheus.io/shard: "0"
    prometheus: prometheus-k8s
  sessionAffinity: ClientIP
