apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- prometheus-operator-clusterRole.yaml
- prometheus-operator-clusterRoleBinding.yaml
- prometheus-operator-deployment.yaml
- prometheus-operator-service.yaml
- prometheus-operator-serviceAccount.yaml
