apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/component: alert-router
    app.kubernetes.io/name: alertmanager
    app.kubernetes.io/part-of: kube-prometheus
  name: alertmanager-main
  namespace: monitoring
