apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- alertmanager-alertmanager.yaml
- alertmanager-secret.yaml
- alertmanager-service.yaml
- alertmanager-serviceAccount.yaml
- alertmanager-podDisruptionBudget.yaml
