apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- prometheus-operator-0alertmanagerConfigCustomResourceDefinition.yaml
- prometheus-operator-0alertmanagerCustomResourceDefinition.yaml
- prometheus-operator-0podmonitorCustomResourceDefinition.yaml
- prometheus-operator-0probeCustomResourceDefinition.yaml
- prometheus-operator-0prometheusCustomResourceDefinition.yaml
- prometheus-operator-0prometheusruleCustomResourceDefinition.yaml
- prometheus-operator-0servicemonitorCustomResourceDefinition.yaml
- prometheus-operator-0thanosrulerCustomResourceDefinition.yaml
