apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- blackbox-exporter-clusterRole.yaml
- blackbox-exporter-clusterRoleBinding.yaml
- blackbox-exporter-configuration.yaml
- blackbox-exporter-deployment.yaml
- blackbox-exporter-service.yaml
- blackbox-exporter-serviceAccount.yaml
